version: '3'

services:
  publisher:
    build:
      context: ./publisher
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
